
package vista.modulos.pedido;

import controlador.ControladorPedido;
import datos.AlmacenDatos;
import modelo.Pedido;
import utilitarios.Constantes;
import vista.comun.Vista;

public class VistaPedido extends Vista {

    //atributos
    private ControladorPedido controlador;
    private SubVistaListar panelListarPedidos;
    public SubVistaDetalle panelNuevoPedido;
    public static Pedido punteroPedido;
    
    public VistaPedido(Constantes.Ordenamiento ordenamiento, Constantes.Busqueda busqueda) {
        //constructor de Vista
        super("Pedido");
        initComponents();      
        controlador = new ControladorPedido(ordenamiento, busqueda);
        controlador.setDatos(AlmacenDatos.pedidos);
        //iniciat Tabs!
        iniciarSubVistas(ordenamiento, busqueda);
        punteroPedido = null;
        this.TAD = " - TAD Lista Doblemente Enlazada";
    }
    private void iniciarSubVistas(Constantes.Ordenamiento ordenamiento, Constantes.Busqueda busqueda){
        panelNuevoPedido = new SubVistaDetalle(controlador, ordenamiento, busqueda);        
        panelListarPedidos = new SubVistaListar(this, controlador, ordenamiento, busqueda);
        pedidoTab.addTab("Listado de Pedidos", panelListarPedidos);
        pedidoTab.addTab("Pedido", panelNuevoPedido);        
        pedidoTab.setSelectedIndex(0); //establecer listado como pestana activa        
        panelListarPedidos.Listar(); // Listar pedidos al iniciar //////////////
    }
    @Override
    public boolean Eliminar(){
        return panelNuevoPedido.Eliminar();
    }
    @Override
    public void Limpiar() {
        panelNuevoPedido.Limpiar();
    }
    @Override
    public Pedido Buscar() {
        //solo si panel detalle esta activo
        if(panelNuevoPedido != pedidoTab.getSelectedComponent())
            return null;
        return panelNuevoPedido.Buscar();
    }
    @Override
    public void Listar(){
        //todo cambiar de penstana
        panelListarPedidos.Listar();
    }
    @Override
    public boolean Guardar() {
        boolean resultado = panelNuevoPedido.Guardar();
        panelListarPedidos.Listar();
        return resultado;
    }
    @Override
    public void Activar(Constantes.Activar tipo) {
        pedidoTab.setSelectedIndex(1);
        panelNuevoPedido.Activar(tipo);
    }
    @Override
    public boolean validarCampos() {
        return panelNuevoPedido.validarCampos();
    }
    @Override
    public void cambiarBusqueda(Constantes.Busqueda busqueda) {
        controlador.cambiarBusqueda(busqueda);
    }

    @Override
    public void cambiarOrdenamiento(Constantes.Ordenamiento ordenamiento) {
        controlador.cambiarOrdenamiento(ordenamiento);
    }

    @Override
    public void Ordenar(boolean asc) {
        if (asc) {
            controlador.ordenar();
        } else {
            controlador.ordenar();
            controlador.invertir(); // Método adicional para invertir el orden de la colección
        }
        Listar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pedidoTab = new javax.swing.JTabbedPane();
        pnlResumen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(pedidoTab);

        jLabel1.setText("Resumen: ....");

        javax.swing.GroupLayout pnlResumenLayout = new javax.swing.GroupLayout(pnlResumen);
        pnlResumen.setLayout(pnlResumenLayout);
        pnlResumenLayout.setHorizontalGroup(
            pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        pnlResumenLayout.setVerticalGroup(
            pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(pnlResumen);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTabbedPane pedidoTab;
    private javax.swing.JPanel pnlResumen;
    // End of variables declaration//GEN-END:variables

    
}
